### ISSUE TITLE
[Docs] Add invitation link to our discord channel

### ISSUE THREAD

**Issue by tnt-codie** [Tea-n-Tech/chia-tea#12]

**Comment by tnt-codie** [comment]
This might help @tnt-manu https://gist.github.com/laundmo/839b74d9cbbf71f25cf772cde57bafb7

**Comment by tnt-manu** [comment]
bot is quiet now in the main chat channel

**Comment by tnt-manu** [comment]
Link for 100 users generated: https://discord.gg/azNjcVPYnY

**Comment by tnt-manu** [comment]
added link to readme
