### ISSUE TITLE
[Monitoring] Harvester connection message wrong

### ISSUE THREAD

**Issue by tnt-codie** [Tea-n-Tech/chia-tea#15]
I unplugged the harvester physically which lead correctly to a disconnect event. A second afterwards a connection message came wrongly. Checking with `$monitors` indeed revealed that the harvester is not under supervision anymore. After the `DELETE` event from the farmer there is oddly an `ADD` event following. This might be related to the logfile checks but further investigation is needed.

**Comment by tnt-codie** [comment]
After about 10 to 15 mins another disconnect message came. This very much looks like being a problem with the logfile since in the logs it takes much longer to not recognize a harvester from the view of the farmer.

**Comment by tnt-codie** [comment]
The add event seems to be caused by an increment of `nDisconnects`. The harvester from the view of the farmer is removed with a "DELETE" event and then again added since an attribute changed.

**Comment by tnt-manu** [comment]
did not find a `nDisconnects` variable in the develop branch. Is this bug still there?

**Comment by tnt-codie** [comment]
@tnt-manu the deployed version is still before your PR changing `nDisconnects` to `nTimeouts`. There are just a few things I don't understand:

1. According to [here](https://github.com/Tea-n-Tech/chia-tea/blob/7b6328f0c507608d6a2471700203f285e2676990/chia_tea/protobuf/data_collection/chia.py#L38) there may not be any message about a harvester from the farmer if either API or logfile say that it is diconnected. So how can this previous message even get through?
2. If this happens with `nDisconnects` it might but must not also happen with `nTimeouts`.

**Comment by tnt-codie** [comment]
`last_message_time` reported by the farmer is last time a message was sent to the harvester and not received!!!
