### ISSUE TITLE
[Docs] Setup Procedure ist quite a mess on windows

### ISSUE THREAD

**Issue by tnt-manu** [Tea-n-Tech/chia-tea#21]
Maybe there is a way to ease the installation process. Several issues:

- The installation requires the c++ build tools to be installed - not a real problem, but we should include this in the video. I don't think there is a way in this phase to ease this as it would require us to ship compiled versions of the requirements - maybe on a later stage
- I found this error: `Processing dependencies for chia-tea==0.0.1 error: sortedcontainers 2.4.0 is installed but sortedcontainers==2.3.0 is required by {'chia-blockchain'}` - really trying to solve it. Environment is Anaconda - first it was a version to low - after update it has this error. Maybe we could make ist less difficult by specifying at least 2.3.0 but as I see it this dependency is not stated directly by us.

**Comment by tnt-manu** [comment]
Next one is: `Installed c:\programdata\anaconda3\lib\site-packages\aiosqlite-0.17.0-py3.8.egg
error: aiohttp 4.0.0a1 is installed but aiohttp==3.7.4 is required by {'chia-blockchain'}`

Maybe there is also a option to force reinstall ?! Maybe this would help.

**Comment by tnt-manu** [comment]
Okay, this got me frustrated so I uninstalled conda and tried with normal standard python - same errors appeared. I suppose there is some neat solution to this that I am not able to see right now.

**Comment by tnt-manu** [comment]
Hm still not there yet. There were some minor errors in the requirements - I will push them into develop but one thing remain:

'win32con' is apparently not found. 
So as I found out (https://stackoverflow.com/questions/35535422/no-module-named-win32com) it is part of the pypiwin32 package - but even after installing it still shows tis error. 

Happes as I run the pytest procedure.

**Comment by tnt-codie** [comment]
@tnt-manu we can fix the version numbers in `requirements.txt` to match the ones of `chia-blockchain`.

**Comment by tnt-manu** [comment]
Can be closed as poetry solves this issues :)
