### ISSUE TITLE
Staging branch non functioning in the monitoring client - type error

### ISSUE THREAD

**Issue by tnt-manu** [Tea-n-Tech/chia-tea#27]
As I was updating farmer and monitoring machines to the latest version on the staging branch the services stopped responding on discord. 
Investigation with systemctl status shows, that the monitoring client has a problem: 

'
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:     event_list, current_state = await get_update_events(
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:   File "/home/chia/chia-tea/chia_tea/chia_watchdog/computer_info_comparison.py", line 175, in get_update_events
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:     new_computer_info = await collect_computer_info(machine_id, chia_dog)
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:   File "/home/chia/chia-tea/chia_tea/utils/logger.py", line 167, in _time_it
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:     return await function(*args, **kwargs)
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:   File "/home/chia/chia-tea/chia_tea/protobuf/data_collection/computer_info.py", line 41, in collect_computer_info
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:     connected_harvesters) = await asyncio.gather(
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:   File "/home/chia/chia-tea/chia_tea/protobuf/data_collection/chia.py", line 63, in collect_connected_harvesters_to_farmer
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]:     HarvesterViewedFromFarmer(
Aug 11 10:53:15 h2938913.stratoserver.net python3[172920]: TypeError: datetime.datetime(2021, 8, 11, 10, 53, 9, 944000) has type datetime.datetime, but expected one of: int, long, float'

Unfortunately I cannot resolve the error looking at the code

**Comment by tnt-manu** [comment]
I try to fix this. Thx

**Comment by tnt-codie** [comment]
I'm closing the issue since it seems resolved now on develop and staging.
