### ISSUE TITLE
[Discord] Catch command errors, log them and send them to the discord channel

### ISSUE THREAD

**Issue by tnt-codie** [Tea-n-Tech/chia-tea#30]
Currently if a discord command gives an error there is no mechanism either logging the error nor is a message given to the user. This needs to be fixed. It would be nice if users would get the error message which makes it easier to report it.

**Comment by tnt-manu** [comment]
What do you think about gathering the stdout and in case of a top level fail catch  save it to log and notify or directly notify the stdout?
