### ISSUE TITLE
[Copy] Change copy process to not use Lockfiles anymore

### ISSUE THREAD

**Issue by codie3611** [Tea-n-Tech/chia-tea#39]
We don't really need lockfiles to check how many plots are being copied. We can simply track all files in the folder (name depends on copy tool ...) with less than the full memory size. We can also detect issues through this since plots which don't change in size are definitely remnants.

**Comment by tnt-manu** [comment]
Seems like I cannot find an easy way to solve this.
While copying - the file size cannot be accessed. st_size does also not work
file.seek(0,2) -> file.tell() does also not work

md5 checks would work but to expensive 
best solution - try to rename it - if it works file copy has finished - if not, its still being copied or used. 
I dont like this. Any ideas @tnt-codie ?

**Comment by tnt-codie** [comment]
It is very odd that the filesize cannot be determined while copy. I mean the os does it somehow otherwise my filebrowser would not be able to display it. The renaming is too dangerous too. It might be a race condition at the end of the copy process.

**Comment by tnt-codie** [comment]
I searched for some answers but could not even find the problem. It should be possible. Maybe there is a mistake somewhere. How about setting up a gist with an example?

**Comment by tnt-manu** [comment]
Problem: https://stackoverflow.com/questions/34586744/os-path-getsize-on-windows-reports-full-file-size-while-copying

Maybe its a Windows related issue ? Will dig into it later

**Comment by tnt-codie** [comment]
@tnt-manu the windows shell can display the filesize. How about simply running 'dir' and parsing the output?
