### ISSUE TITLE
[Monitoring] Remove Midnight reset 

### ISSUE THREAD

**Issue by tnt-manu** [Tea-n-Tech/chia-tea#41]
In earlier days we reset the harvester informations everyday at 0:00 
This is not neccesary anymore and can be removed.
It might be a good idea to implement a discord command to manually reset the database in the case a user would like to do this (e.g. to reset missed challenges counts etc.)

**Comment by tnt-codie** [comment]
Hmm, we could add a reset every attribute but not sure if people really want that. Usually they just want daily, weekly or monthly reports.
