### ISSUE TITLE
[Discord] Give a message if a machine is not being monitored anymore

### ISSUE THREAD

**Issue by tnt-codie** [Tea-n-Tech/chia-tea#6]

**Comment by tnt-manu** [comment]
No monitoring means a timeout on the machine right? 
So after not having heard for a minute or so we would throw a message onto discord.

**Comment by tnt-codie** [comment]
Yes currently we log the time when the machine responded. This should be below a minute. This is a great indicator that the machine has a general disconnect to the internet.
